name: CI

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  sunstone:
    name: StandardAPI Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        encoder:
          - jbuilder
          - turbostreamer
        ruby-version:
          - 3.2
        rails-version:
          - 7.0.8
          - 7.1.2
        postgres-version:
          - 15


    steps:
      - name: Install Postgresql
        run: |
          sudo apt-get -y --purge remove $(sudo apt list --installed | grep postgresql | awk '{print $1}')
          sudo apt-get install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update
          sudo apt-get -y install postgresql-${{ matrix.postgres-version }}-postgis-3
          sudo systemctl start postgresql@${{ matrix.postgres-version }}-main.service
          sudo systemctl status postgresql@${{ matrix.postgres-version }}-main.service
          sudo pg_lsclusters
          sudo -u postgres createuser runner --superuser
          sudo -u postgres psql -c "ALTER USER runner WITH PASSWORD 'runner';"

      - name: Install YAJL
        run: |
          wget 'https://github.com/lloyd/yajl/archive/refs/tags/2.1.0.tar.gz'
          tar -xvf '2.1.0.tar.gz'
          cd 'yajl-2.1.0' && ./configure && make && sudo make install
          sudo ldconfig

      - uses: actions/checkout@v4

      - run: |
          echo 'gem "rails", "${{ matrix.rails-version }}"' >> Gemfile
          echo 'gem "wankel"' >> Gemfile
          sed -i -e "s/spec.add_development_dependency 'jbuilder'/spec.add_development_dependency '${{matrix.encoder}}'/" standardapi.gemspec

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - run: bundle exec rake test